project:
  type: website

website:
  title: "CyberTraining"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects/index.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
      - href: presentation.qmd
        text: Presentations
      - href: photos.qmd
        text: Photos
      - href: about.qmd
        text: People
  page-footer:
    center: "Built with Quarto"
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    smooth-scroll: true
    include-in-header: mathjax-config.html

bibliography: references.bib
